### ISSUE TITLE
[PE-D][Tester D] Error message not showing all errors for edit owner

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T13-3/tp#205] opened 2024-11-08 16:57 UTC
Error inputted in phone number & email
- Error message only shows error for phone number

![image.png](https://raw.githubusercontent.com/thenosewizard/ped/main/files/1e6cd1f4-cb6f-400a-9bba-7ca60f7c1671.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: thenosewizard/ped#2

**Comment by jloh02** [comment] 2024-11-09 17:20
Duplicate of #197

**Closed by jloh02** 2024-11-09 17:20 UTC
